spdx/spdx-online-tools

- src/api/models.py
- src/api/views.py
> Bug Fix: File saved twice by API #9

- src/api/models.py
- src/api/serializers.py
- src/api/tests.py
- src/api/views.py
- src/app/templates/app/convert.html
- src/app/tests.py
- src/app/views.py
> Add options to TagToRdf conversion #8

- README.md
- src/api/models.py
- src/api/serializers.py
- src/api/tests.py
- src/api/urls.py
- src/api/views.py
Closes: https://github.com/spdx/spdx-online-tools/issues/10
Implemented an API for check license method and the necessary tests.
The input file is stored in `app/media/api/`.
Input file is read to string variable to be passed as arguement.
> API for check license method

- requirements.txt
- src/api/models.py
- src/api/serializers.py
- src/api/views.py
- src/app/models.py
- src/app/views.py
- src/requirements.txt
- src/src/settings.py
Do we need to update the Django version also, as you mentioned the current is the LTS version and it also works fine.
PR for issue: #24
> Add support for Python3

- .gitignore
Closes : https://github.com/spdx/spdx-online-tools/issues/20
> Update .gitignore to ignore to ignore .DS_store

- src/app/templates/app/register.html
Added the CSRF token to the form data and made the AJAX call async so that we can easily return the result.
> Fix user register bug

- src/app/static/css/editor.css
- src/app/static/css/editor/diffview.css
- src/app/static/js/editor/difflib.js
- src/app/static/js/editor/diffview.js
- src/app/static/js/editor/script.js
- src/app/static/js/editor/treeview.js
- src/app/templates/app/editor.html
- src/app/urls.py
- src/app/views.py
- src/examples/xml-schema.xsd
- src/requirements.txt
Clicking the Submit Changes button opens up diff in a modal.
> Add diff and validate feature to editor

- NOTICE
- src/app/static/js/editor/script.js
- src/app/templates/app/editor.html
- src/app/tests.py
- src/app/utils.py
- src/app/views.py
The update file bug has been fixed in the GitHub integration.
> Improve Pull Request feature 

- src/app/static/js/editor/script.js
- src/app/static/js/editor/treeview.js
- src/app/templates/app/editor.html
- src/app/utils.py
- src/app/views.py
- src/src/settings.py
* Add documentation for the code.
* Fix a bug in pull request feature.
* Remove GitHub keys from `settings.py` file 
> Add documentation for XML Editor code

- README.md
- src/app/tests.py
* Add unit tests for license submittal features.
> Tests license submittal

- src/app/static/js/editor/treeview.js
@goneall  The reordering of the tags has been fixed 
Please test and provide suggestions :slightly_smiling_face:
> Fix re-ordering of elements in tree editor

- requirements.txt
> Update requests version to resolve security vulnerability

- .gitignore
- README.md
- src/app/templates/app/base.html
- src/app/templates/app/login.html
- src/app/templates/app/submit_new_license.html
- src/app/views.py
- src/src/settings.py
Resolves issue #54 by authenticating the user through github before submitting a new license request.
Much of the logic and some of the code was copied from the github authentication used in the XML pull request code.
> GitHub license submit

- .travis.yml
- README.md
- src/api/serializers.py
- src/api/tests.py
- src/api/views.py
- src/app/forms.py
- src/app/tests.py
- src/app/utils.py
- src/app/views.py
- src/src/settings.py
* Fix test cases
* Improve README file
* Add email prefill feature in Submit new license form.
* Add travis file
* Improve compatibility with Python3
Fix #54 #63
> Improvements in Submit new license

- src/app/forms.py
> Fix error when posting a new license submittal

- src/app/forms.py
- src/app/templates/app/submit_new_license.html
#64 
rename the "Notes" field to "Comments", make the text box bigger, and move it to the bottom of the form
> Rename Note to comment, change to textarea, move to bottom

- .travis.yml
- src/app/tests.py
- src/src/secret.py
Add secret.py file for storing github API credentials as well as fix the travis build error of 'geckodriver' needs to be in PATH error
Fixes #72 
Fixes #83
> Add secret.py file and fix travis build error

- src/app/templates/app/license_information.html
- src/app/tests.py
- src/app/urls.py
- src/app/views.py
> Add edit xml functionality on license request page 

- src/app/templates/400.html
- src/app/templates/403.html
- src/app/templates/404.html
- src/app/templates/500.html
The home page button in error templates was not working, now it takes the user to the
home page after clicking on it.
> Fix button in error templates

- README.md
Two of the links mentioned in the readme were dead and not working so, i have updated them in this PR.
> Fix links in README file

- src/app/views.py
- src/src/settings.py
For #95 
I have added to urls to the settings file.
> License submit url

- src/app/models.py
- src/app/templates/app/archive_requests.html
- src/app/templates/app/base.html
- src/app/templates/app/license_information.html
- src/app/tests.py
- src/app/urls.py
- src/app/views.py
> Add archive license request feature

- src/app/forms.py
- src/app/models.py
- src/app/templates/app/submit_new_license.html
- src/app/tests.py
- src/app/views.py
> Change the comments field to report the comments in the issues

- src/app/templates/app/archive_requests.html
- src/app/templates/app/base.html
- src/app/templates/app/license_requests.html
Fixed issue #94 Convert mouse pointer on hover:
Added css for `archive-requests.html` and `license-requests.html` files inside base.html
Fixed the issue with the Archive/unarchive button by adding type=`'button'` inside `<input>` tag.
> Convert mouse pointer on hover Issue #94

- src/app/views.py
Fixes #105 
Tested and working [here](https://github.com/spdx/TEST-LicenseList-XML/issues/12).
> Display of license header in github issue

- src/app/templates/app/submit_new_license.html
> Change focus on error and scroll to the top when submitting a new license

- src/app/templates/app/submit_new_license.html
> Add instructions for form fields in license submit

- src/app/templates/app/submit_new_license.html
> Add validations for license submittal fields

- requirements.txt
> Update django rest framework to ~> 3.9.1

- requirements.txt
- src/app/templates/app/base.html
- src/app/templates/app/submit_new_license.html
- src/app/tests.py
- src/app/utils.py
- src/app/views.py
To Check if the submitted licenses matches with that of the once that are already rejected or yet not approved licenses by the legal team.
> Compare submitted licenses with the rejected as well as yet not approved licenses.

- src/api/oauth.py
- src/app/utils.py
> Fix minor url issues in app utils and api oauth file

- src/app/views.py
Change file extension to .xls in convert view for spreadsheets. Fix issue #120.
> change file extension to .xls issue#120

- src/app/templates/app/license_namespace_requests.html
- src/app/templates/app/submit_new_license.html
- src/app/templates/app/submit_new_license_namespace.html
Updated the SPDX legal team mailing address to the correct one.
Fixes #158
> Update SPDX legal team mailing email address

- src/app/templates/app/archive_namespace_requests.html
- src/app/templates/app/archive_requests.html
- src/app/templates/app/check_license.html
- src/app/templates/app/license_namespace_requests.html
- src/app/templates/app/license_requests.html
- src/app/templates/app/promoted_namespace_requests.html
- src/app/templates/app/submit_new_license.html
- src/app/templates/app/submit_new_license_namespace.html
Fixed UI overflows in various places in the application.
Example:
> Fix overflows in the UI

- src/app/templates/app/archive_requests.html
- src/app/templates/app/license_requests.html
- src/app/tests.py
- src/app/utils.py
- src/app/views.py
The users will now need to login in to archive or unarchive the request.
Only, the repo collaborators will be able to archive the request.
Fixes #107
> Solve archive requests issue #107

- README.md
Updated path of some files in README.md to make minor things more clear. Since in almost every part of the README.md file, we are using path relative to parent directory, I had updated some paths so that their location become more clear.
Signed-off-by: shubham.gupta2956 <shubham.gupta2956@gmail.com>
> Updated path of some files in README.md

- docker-compose.dev.yml
- docker-compose.prod.yml
- src/app/utils.py
- src/src/secret.py
Signed-off-by: K mehant <411843@student.nitandhra.ac.in>
> Get redis host from env variable SPDX_RDIS_HOST

- README.md
- src/app/forms.py
- src/app/static/js/editor/postscreenshot.js
- src/app/templates/app/submit_new_license.html
- src/app/urls.py
- src/app/utils.py
- src/app/views.py
- src/src/secret.py
- src/src/settings.py
This is to resolve issue #216 
> Add configuration for screenshot repository

- src/app/templates/app/base.html
We are show "SPDX Validation Tool" in the top left corner of the website.
Since this tool does more than that, changing the name to "SPDX Online Tool"
> Change name to SPDX Online Tool

- .gitignore
- docker-compose.dev.yml
- src/api/tests.py
- src/api/views.py
- src/app/templates/app/check_license.html
- src/app/templates/app/compare.html
- src/app/templates/app/convert.html
- src/app/templates/app/submit_new_license.html
- src/app/tests.py
- src/app/views.py
Resolves issue #211 
Resolves issue #215 
Resolves issue #226 
Resolves issue #227 
Note that there are separate commits for each of the issues if you prefer to review individually.
Also note that the development docker-compose file now requires a .env file at the root of the project to hold sensitive environment variables.
> Fix various issues found in production

- src/app/views.py
- src/app/widgets.py
Resolves issue #228 - missing add image
> Resolves issue #228 - missing add image

- README-PRODUCTION.md
- docker-compose.prod.yml
- requirements.txt
> Resolve issue #222 - stale spdx-license-matcher

- data/nginx/app.conf
Signed-off-by: Gary O'Neall (Production) <gary@sourceauditor.com>
> Fix issue #235 GitHub oauth redirect URI mismatch

- requirements.txt
This may resolve issue #142 
NOTE: This requires an update to the database, you need to run
`python src/manage.py makemigrations`
`python src/manage.py migrate`
> Update the version of social-auth-app-django

- src/app/forms.py
- src/app/templates/app/submit_new_license.html
- src/app/utils.py
- src/app/views.py
Resolves issue #240 
Added project examples:
The example URL's are added to the issues.  Note that the project URL's are not added to the database.
For an example, see: https://github.com/spdx/TEST-LicenseList-XML/issues/92
> Resolves issue #240 - update submit license fields

- src/app/templates/app/submit_new_license.html
> Resolve issue #252 - add text to top of license submittal page

- src/app/templates/app/validate.html
> Fix issue #255 - use the correct values for SPDX file formats for validate

- src/app/templates/app/about.html
Added names of people who worked on the tool during past GSoCs and provided significant contributions.
> Add major contributor names on about page

- data/nginx/app.conf
- docker-compose.prod.yml
- src/app/utils.py
- src/src/settings.py
> Final production changes - improve production security

- data/nginx/app.conf
- docker-compose.prod.yml
> Update configuration to support let-encrypt challeng

- src/app/formatxml.py
- src/app/utils.py
- src/app/views.py
> Fix encoding issues for open and XML parsing

- requirements.txt
- src/app/utils.py
2 fixes for issues identified during the release testing.
> Fixes for the production release 1.0.2

- supervisor_api.conf
Works around issue #289 - the real fix would be to resolve the 2 performance issues mentioned in the issue.
> Increase the timeout from 60 seconds to 240 seconds

- docker-compose.prod.yml
- src/src/version.py
> Change version of deployed to 1.0.3

- src/src/version.py
The new SPDX java tools includes a very significant performance improvement for parsing tag/value.  This, together with PR #318 should resolve issue #306 
> Update java tools to version 1.0.2

- dockerfile.dev
- dockerfile.prod
> Change Java version to OpenJDK:slim

- requirements.txt
- src/app/core.py
- src/app/utils.py
Resolves issue #354 
Also adds back the match status (e.g. "perfect match" or "close match") which was lost during the refactoring.
> Resolve issues with license compare

- docker-compose.prod.yml
- src/src/version.py
Updates the Java tools to the latest version.
Update the version for the online tools and java tools in the application.
> Update Java tool version and bump online tool version numbers

- requirements.txt
Resolves an issue in production preventing the server to start
> Update the gevent version

- requirements.txt
Includes a fix for issue #361 
> Update to version 2.4 of the spdx-license-matcher

- src/api/models.py
- src/app/forms.py
Resolves issues:
* https://github.com/spdx/spdx-online-tools/issues/336
* https://github.com/spdx/spdx-online-tools/issues/365
Signed-off-by: Sebastian Crane <seabass-labrax@gmx.com>
> Add "Don't know" option for OSI approval status

- wsgi_conf.py
> Add gunicorn timeout of 4 min

- src/app/templates/app/submit_new_license.html
As asked here: https://github.com/spdx/spdx-online-tools/issues/367
> removed "Email address" field

- src/app/templates/app/convert.html
Fix #394 Inconsistency in menus between Convert and Validate 
Signed-off-by: Marc-Etienne Vargenau <marc-etienne.vargenau@nokia.com>
> Fix #394 Inconsistency in menus

- src/app/templates/app/submit_new_license.html
- src/app/views.py
accompanying changes to #379 
Signed-off-by: Jilayne Lovejoy
> remove userEmail from license request tool

- README.md
fixes https://github.com/spdx/spdx-online-tools/issues/402
Signed-off-by: Armin Tänzer <armin.taenzer@tngtech.com>
> changed the dependencies link to point to the new spdx java tools

- src/app/templates/app/convert.html
- src/src/version.py
Also updates the SPDX Java tools library to version 1.1.3
> Add support for RDF/TTL format in convert

- src/app/utils.py
change master to main references to license list repo
@goneall - please check if this looks right!
Signed-off-by: Jilayne Lovejoy
> Update references to main

- src/app/core.py
It looks like the NTIA Conformance Checker PR replaced the core.license_checker_helper which broke check check license. This commits puts back the original code.
> Replace the check_license method

- requirements.txt
- src/app/templates/app/about.html
- src/app/views.py
- src/src/version.py
Also adds the NTIA conformance checker version to the about page
> Update NTIA conformance checker to version 0.1.0

- src/app/utils.py
> Decode the base64 file information for xml file commit

- src/app/templates/app/submit_new_license.html
- src/app/views.py
Fixes #411
Also fixes a broken link to license matching guidelines.
> Remove email from license submit

- src/app/templates/app/editor.html
- src/app/utils.py
- src/src/settings.py
> Only use test license XML repo when in debug

- requirements.txt
- src/src/version.py
This update provides a 100X or better performance improvements for very large SPDX files.
> Update SPDX tools to version 1.1.5 and Python tools to released version

- requirements.txt
- src/app/core.py
- src/app/templates/app/ntia_conformance_checker.html
- src/app/views.py
~~Note: This is currently not working due to an import issue~~
> Use SbomChecker for NTIA check for min feature

- src/api/tests.py
Addressed followings,
- Fix https://github.com/spdx/spdx-online-tools/issues/341
- Fix https://github.com/spdx/spdx-online-tools/issues/343
- Fix https://github.com/spdx/spdx-online-tools/issues/344
> Fix SubmitLicenseModelsTests tests in python3 branch

- src/app/tests.py
Adding comments as @rtgdk suggested in [https://github.com/spdx/spdx-online-tools/issues/201#issuecomment-1465102798](https://github.com/spdx/spdx-online-tools/issues/201#issuecomment-1465102798)
> #201 Adding comments to test_promote_license_namespace_feature

- src/app/utils.py
Fixes #462 but may re-introduce unit test failures issue #202 by partially reverting PR #444
> Remove UTF-8 convert in check_spdx_license

- src/src/version.py
Also update the version number for release
> Update Java tools to version 1.1.7

- src/app/templates/app/submit_new_license.html
> Corrected TYPO

- src/app/static/js/utils.js
- src/app/templates/app/license_diff.html
- src/app/templates/app/submit_new_license.html
- src/app/views.py
- Small fixes for code maintenance 
- Renamed some variable for better readability
- Fixed matching with true value
> Small code maintenance fixes

- src/app/forms.py
- src/app/templates/app/submit_new_license.html
- Added the GUI changes for the license and exceptions as discussed in the doc shared by @jlovejoy 
@rtgdk can you review this once and let me know if anything else needs to be changed in this
> Added the GUI changes

- src/app/templates/app/base.html
> Update spdx logo on navbar - Fixes #505

- docker-compose.prod.yml
- src/src/version.py
- Updated spdx online tools version
- Updated docker production with new version image
> Update tools version to 1.2.2 for release

- dockerfile.dev
- dockerfile.prod
- src/src/settings.py
- Intended to solve #511 
@goneall have changed `dockerfile.dev` and added the `collectstaic` command there. This should work and all the static files should get collected. Can you try that once and do let me know if anything else needs to be done in this.
> Added STATIC_ROOT and changed docker.dev

- README-PRODUCTION.md
> README-PRODUCTION issues

- requirements.txt
> Update ntia-conformance-checker and spdx-tools to latest

- dockerfile.dev
- dockerfile.prod
- src/src/version.py
> Update Java JVM to Java 17

- src/api/serializers.py
- src/api/tests.py
- src/api/views.py
- src/app/forms.py
- src/app/generateXml.py
- src/app/models.py
- src/app/tests.py
- src/app/urls.py
- src/app/utils.py
Remove unused imports in Python code as reported by Pylance and Ruff
> Remove unused imports in Python code

- requirements.txt
Update numpy, requests, and lxml to its latest patch updates:
- numpy 1.22.0 -> 1.22.4
- requests 2.32.0 (yanked version) -> 2.32.3
- Will also fix #546 
- lxml 4.9.1 -> 4.9.4
> Update patch versions in requirements.txt

- src/src/version.py
> Update Java tools library to version 2.0.0-RC2

- src/app/generateXml.py
- src/src/settings.py
Improved the generateXml.py file along with a typo fix in settings.py
> Update generateXml.py and Fix typo in settings.py
