src/src/settings.py
Making the file path work in a platform independent manner - necessary to run on a Windows platform
=> Fixing file path to the tools jar file

.gitignore, src/app/templates/app/submit_new_license.html, src/app/utils/github_utils.py, src/app/views.py
Any suggestion please let me know @goneall @rtgdk
=> GitHub issue creation

src/app/templates/app/license_information.html, src/app/views.py
Changed the method of formatting from CData to using paragraph tags in the XML editor.
Also added linefeeds around the XML tags to format a bit better - it isn't a very good pretty printer, but it looks better than no linefeeds at all.  We should change to a better XML pretty printer once everything is merged.
@gaalocastillo If you could review the changes
@rtgdk If you could also review and if it looks OK, merge this into text-field-format, then merge text-field-format into the license-submittal branch before merging with master
=> Change method of formatting the text to use the paragraph elements

src/app/templates/app/license_information.html, src/app/views.py
I have made some changes on the way the license **text field** is displayed on the license information view:
- HTML tags are supported on the license text field without creating any conflicts with the license XML creation.
- Linefeeds have been replaced with `<br>` tags.
- The unnecessary `<text>` tag surrouding the text field has been removed.
Please let me know any change/suggestion @rtgdk @goneall . I think my solution could follow cleanner approach.
=> License text field format

src/app/templates/app/base.html
The check license link appeared twice on the navbar.
=> Remove duplicate link from navbar

src/api/views.py, src/app/views.py
Add a license request URL field to the description of the issue generated in the license submittal feature. It will help in tracking the license faster.
=> Add license request url to the generated issue description

src/app/templates/app/submit_new_license.html
Add links for GitHub login in the popup in the license submission form. Edit 'Licenses list to License list'.
Fixes for issue #117.
=> Add links to popup in license submitting form issue#117

src/app/utils.py
Import License Request from app.models to overcome the error raised in form submission - 'License Request does not exist', line 440 in utils.py.
Issue #148
=> Import LicenseRequest and namespace to utils

src/app/templates/app/modal.html
I have tested for many cases and this size of modal seems to be most appropriate for any type of errors.
Current modal view:-
New modal view:-
PS- Since the CSS properties of this modal are coming from bootstrap, I had to use inline CSS for it. 
Signed-off-by: shubhamgupta2956 <shubham.gupta2956@gmail.com>
=> Increase modal view to remove overflowing errors.

src/app/views.py
Currently, when the user uploads a file having white spaces in its name,
it is not validated as the file name is changed due to replacement of
whitespace by "%20". This commit replaces it with whitespaces so that
the correct file can be validated.
Fixes: #174 
Signed-off-by: shubham.gupta2956 <shubham.gupta2956@gmail.com>
=> Fix validation for file having whitespaces in their name

src/api/tests.py, src/api/views.py, src/app/templates/app/compare.html, src/app/templates/app/convert.html, src/app/templates/app/validate.html, src/app/tests.py, src/app/views.py
The new Java tools library has been significantly re-written and adds support for additional JSON file.
Note: There is some loss functionality in the convert function.  It no longer supports converting to HTML.
The HTML and JavaScript UI has been update to reflect the new files supported.
Also note that the default spreadsheet format is now XLSX rather than XLS (although XLS is also supported).
=> Use the new tools-java adding support for JSON, YAML, XLSX, and XML file formats

README.md
Minor update to the README file to provide instructions to run the development Docker image.
Instructions based on the documentation in PR #188
=> Add docker instructions to README file

src/app/templates/app/submit_new_license.html
Remove the unnecessary CodeMirror editor from the submit new license HTML file. This does not seem to be used and causes an error to be displayed in the web browser console.
This resolves issue #264 
=> Remove unnecessary JavaScript editor inclusion

src/app/utils.py, src/app/views.py
This  resolves issue #267 by only converting to unicode if the licenseText is not already of type unicode.
=> Resolve encoding exception for UTF8 encoded license texts

src/src/settings.py
Fix bug where DEBUG is not properly interpreted when using system variables
=> Update debug settings

src/app/templates/app/convert.html
Fixes #241
This PR adds automatic filename in url `app/convert/` according to the file entered after removing the extension of the file.
Example: `test.extension` will have default Converted File Name as `test`
=> Fix #241: Added automatic filename in convert

src/src/settings.py
Authentication Backends for GoogleOpenId and YahooOpenId are [depreciated](https://github.com/python-social-auth/social-core/issues/472) in [python-social-auth](https://github.com/python-social-auth/social-core/blob/master/CHANGELOG.md) 4.0 . Thus removing these fixes module load error in `app.tests.ProfileViewsTestCase` .
=> Remove depreciated GoogleOpenId and YahooOpenId

src/api/tests.py, src/api/utils.py, src/api/views.py, src/app/core.py, src/app/utils.py, src/app/views.py
Fixes #287 
The PR adds support for a common utility that contains all the core logic required for the SPDX Online tools. Both App and Api make use of this utility so, we don't have to test the app and api individually. It reduces redundancy and makes it easy to test the modules and maintain them.
=> Merge App and Api by creating a common utility for core logic

dockerfile.prod
Resolves an incompatibility with the Python3 changes
=> Update psycopg2 version

src/api/admin.py, src/api/models.py, src/api/serializers.py, src/api/tests.py, src/api/urls.py, src/api/views.py, src/app/admin.py, src/app/formatxml.py, src/app/forms.py, src/app/models.py, src/app/urls.py, src/app/utils.py, src/app/views.py, src/src/urls.py
Let us use our own recommendations:
* add `SPDX-License-Identifier`
* add `SPDX-FileCopyrightText`
in source files.
Signed-off-by: Marc-Etienne Vargenau <marc-etienne.vargenau@nokia.com>
=> Add SPDX-License-Identifier and SPDX-FileCopyrightText

src/app/templates/app/submit_new_license.html
The required text has been added next to submit_new_license.html file.
New Screen:
=> Added the text "If not known, put 'Unknown')" 

.github/workflows/django.yml
This only impacts the CI Github Action workflow.
The previous version (3.7) is no longer supported.
=> Bump Python version to 3.8 in the CI

src/app/templates/app/base.html
Removing the namespace feature for now since the namespace functionality has not be decided.
Once we decide on the namespace functionality, we can re-enable the menu.
=> Remove the namespace menu items

dockerfile.dev, dockerfile.prod
Fixes issue #404
Version 3.10.6 is the version of Python currently running in prod.
=> Fix Python version in docker to 3.10.6

src/api/views.py, src/app/core.py, src/app/utils.py, src/app/views.py
Currently all the information is inside a single string. 
The new output looks like the following:
```json
{"matched_license": null, "match_type": "No match", "all_matches": {}}
```
```json
{"matched_license": "Apache-2.0", "match_type": "Standard License match", "all_matches": {"Apache-2.0": 0.9813657538916032, "SHL-0.51": 0.9398223577022127, "SHL-0.5": 0.9392793360647127, "ECL-2.0": 0.958951030238159}}
```
```json
{"matched_license": "BSL-1.0", "match_type": "Perfect match", "all_matches": {"BSL-1.0": 1.0}}
```
Is there a reason while all the uploaded files are saved on disk and in the database? This seems very unnecessary and only consumes a lot of disk space over time.
=> Make /api/check_license more machine readable

README-PRODUCTION.md, dockerfile.dev, dockerfile.prod
The previous OpenJDK container is deprecated and contains a number of known vulnerabilities
=> Update docker files to use eclipse-temurin

src/src/version.py
- Resolves https://github.com/spdx/spdx-online-tools/issues/420
Use the Java tools and NTIA Conformance checker package themselves to obtain their version for the About page instead of hard coding.
=> Update versions from packages themselves

src/app/templates/app/about.html, src/app/templates/app/base.html, src/app/templates/app/index.html
- Added a link back to the main SPDX main page in the upper right corner instead of the upper left corner since already there is a link to the home page of _spdx-tools_ in the left corner, so confusion can occur.
=> #288 Create a link back to the SPDX main website

src/app/tests.py, src/app/utils.py
- Two required fields (exampleUrl,  comments) were missing in the request and they were added.
- Byte type patterns were not converted to utf-8 strings in line 518 and 519 in [src/app/utils.py](https://github.com/spdx/spdx-online-tools/blob/main/src/app/utils.py) (This error was raised when the first point is fixed)
=> #202 Fixing Unit test failure - test_post_submit

src/app/views.py
As [this issue](https://github.com/spdx/spdx-online-tools/issues/184) points out, there are redundant code segments in the `app/views.py`. This PR will removes few redundant code segments from there.
Additionally, have removed unused imports from `app/views.py`.
=> Limit code repetition in `app/views.py`

src/api/tests.py
- Fixes #282 
- Fixed the unit tests by removing the `CheckLicenseFileUpload` field which is not required
- The model does not exist which was causing the issue in the tests
=> Fixed API Tests for ConvertFileUploadTests #282

src/api/views.py, src/app/templates/app/submit_new_license.html, src/app/utils.py, src/app/views.py
=> Fixing Redirect on Successful License Submission

src/app/core.py, src/app/utils.py
Fixing #376 
Changes on top of https://github.com/spdx/spdx-online-tools/pull/460 
Works for other illegal characters as well like `SPDXTagExample-v2.2:#%rohit.spdx`
All illegal characters list taken from - https://www.mtu.edu/umc/services/websites/writing/characters-avoid/
=> Substitute illegal characters in filename to hyphen

README-PRODUCTION.md, docker-compose.prod.yml, dockerfile.prod, src/src/version.py
Fixes #487
Also bumps version to 1.2.1
=> update docker production file

src/app/core.py
- Made the changes suggested by @vargenau and @goneall which will help better format the error messages and warnings we receive in the online tools.
-  Solves #494
=> Intended to solve #494

src/app/static/js/utils.js, src/app/templates/app/license_diff.html, src/app/templates/app/submit_new_license.html, src/app/views.py
- Added new `check license diff` button on the `submit new license` page itself so that the user does not need to change the tab
- Solves #346 
- Changed the `submit_new_license.html` to handle this and call the `license_diff` function
=> Added button to check license diff on Submit new License Page #346

dockerfile.dev, dockerfile.prod
Resolves an issue that if there are existing files, there is a prompt to overwrite which causes the docker build to fail
=> Add --noinput to static file generation

README-PRODUCTION.md, docker-compose.prod.yml, dockerfile.dev, dockerfile.prod, requirements.txt
- Update the version in the docker-compose.prod file 
- Update the version of the base image to resolve vulnerabilities 
- Update the version of license checker to resolve vulnerabilities Update production dockerfile to automatically migrate and populate the license database
- Update the production documentation to clarify deployment procedures
=> Updates for deployment

requirements.txt, src/app/templates/app/base.html, src/app/templates/app/dots.html, src/app/urls.py, src/app/views.py
- Added a "Visual Editor" tab to the nav bar.
- Embedded "dots" in an iframe using https.
- Wrapped "block1" with a "dots" block so the iframe could stretch the entire height. If the "dots" block don's have any content then "block1" is rendered as usual, so it shouldn't affect existing templates.
=> add dots in iframe

.gitignore, requirements.txt, src/app/core.py, src/app/templates/app/compare.html, src/app/templates/app/convert.html, src/app/templates/app/validate.html, src/app/utils.py, src/src/version.py
Changes include:
- Updating the SPDX Java Tools to version 2.0.0
- Changes to the API to the Java tools
- Add V3 JSON-LD as a supported file type in verify
- Add V3 JSON-LD as a supported output file type in convert
- Changed file type selections to prepend the spec version
- Updated the license matcher version to 2.7 (supports SPDX 3)
=> Support SPDX Spec version 3

requirements.txt, src/app/core.py, src/app/templates/app/ntia_conformance_checker.html
Changes to ntia-conformance-checker related code, to prepare it for [more compliance checkers](https://github.com/spdx/ntia-conformance-checker/pull/224) in the future.
These changes are effectively only in the UI side for now and there's nothing change on the backend side apart from the upgrade of the library.
- Update ntia-conformance-checker version to 3.0.2
- Add compliance selector to UI
- There's only one option now, which is the selected default "ntia"
- Add a (commented) code to get compliance request value
- If the value is not exist, use "ntia" as default
- This value will be used post-3.0.2 to let SbomChecker knows which compliance it should check against
- Remove unused imports
- Fix few typos
=> Add ntia-conformance-checker compliance selector to UI

src/app/templates/app/check_license.html
- Add a usage description to Check License UI, based on https://github.com/spdx/spdx-online-tools/issues/527#issuecomment-2564809534
- Also add a missing closing `</div>` in the HTML
=> Add usage description to Check License UI

src/app/templates/app/convert.html, src/app/templates/app/ntia_conformance_checker.html, src/app/templates/app/validate.html, src/app/templates/app/xml_upload.html
- Use `<div>` (instead of `<p>`) for filename display in drag & drop area, so the text will be centred like other HTML elements in the same pane
- Update heading to match the tool title (see current Compare tool for an example)
- Put "V2" into File Type selections, for NTIA Conformance tool
--
**NTIA Conformance tool:** the heading is not descriptive and the filename ("No file selected") is off to the left
**Compare tool:** the heading is descriptive and the filename is centred
=> Descriptive title + Centred filename in drag&drop

src/app/templates/app/dots.html
Updated inline CSS in `dots.html` to fix layout issues.
Fixes #551
Tested on: Firefox 135 (Fedora Workstation 41)
=> Fixed Visual Editor narrow window issue in Firefox
